# Change these first
owner: Cysime # Your GitHub username
repo: GlaceonStatus # Your Github repository name

# Add your sites here
sites:
  - name: Media Center
    url: https://media.glaceon.net
  - name: Seedbox Library
    url: https://lib.glaceon.net
  - name: Node - Apple Jack
    url: $AJ
  - name: Node - Big Mcintosh
    url: $BM
  - name: Node - Discord
    url: $DS
  - name: Node - Fluttershy
    url: $FS
  - name: Node - Rarity
    url: $RR
  - name: Node - Starlight Glimmer
    url: $SG

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.glaceon.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /GlaceonStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Glaceon Cloud Status
  introTitle: "**Glaceon Cloud** Status Service"
  introMessage: 在这里检查Glaceon Cloud的所有网络服务状态

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
